version: '2'
services:
  db:
    image: postgres:14-alpine
    env_file: .env
  web:
    build: .
    command: uvicorn search_smartly.asgi:application --host 0.0.0.0 --port 8000 --reload
    env_file: .env
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db