# Generated by Django 4.2.10 on 2024-02-21 23:11

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PoI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('external_id', models.BigIntegerField(verbose_name='external id')),
                ('lon', models.FloatField(verbose_name='longitude')),
                ('lat', models.FloatField(verbose_name='latitude')),
                ('category', models.CharField(max_length=150, verbose_name='category')),
                ('ratings', django.contrib.postgres.fields.ArrayField(base_field=models.DecimalField(decimal_places=2, max_digits=12), size=None)),
            ],
            options={
                'verbose_name': 'point of interest',
                'verbose_name_plural': 'point of interests',
            },
        ),
    ]
